### ISSUE TITLE
how to make get vehicle annotations

### ISSUE THREAD

**Issue by guofengpeng** [aras62/PIEPredict#10]
hi，sir. I want to make myself dataset. Could you tell me how you make the annotations ? I have know how to use cvat to annotate the video clips.

**Comment by aras62** [comment]
Hi,
I am not sure what you are asking us. As we mentioned, we used CVAT to annotate our dataset. If you need help with that please refer to the CVAT home page and follow the instructions. They also have a big community that answers questions if you have any difficulties.

**Comment by guofengpeng** [comment]
emmmm...maybe I am not expressive clearly...
As you said, the annotation file include 'annotations.zip', 'annotations_attributes.zip' and 'annotations_vehicle.zip'. By using cvat, I can get person label include bbox and attribute (id, occlusion,cross, action, look and gesture).
however I donot know how to get 'vehicle info', include gps speed, obd speed, pitch, roll, yaw and so on .

**Comment by ykotseruba** [comment]
Hi, 
the vehicle information was obtained from the vehicle CAN bus while the video of the drive was recorded. We used a dashboard camera that recorded video, GPS, and vehicle data. Please see the paper for details.
