### ISSUE TITLE
Trajectory Prediction

### ISSUE THREAD

**Issue by amineamali** [aras62/PIEPredict#11]
I have a question please.
It is logical that the tracks might have different length appearance in the video.
Is there a phase of pre-processing that you make them in the same size of length(which I didn't found it in function get_data) or the model deal with it automatically ?

Thank you

**Comment by aras62** [comment]
Hi, 

You are correct, it is logical to make them the same size (perhaps by padding). what we did, however, is that we excluded shorter tracks (below  obs_lenght+pred_length) when reading the raw annotations from the data interface. There were very few cases excluded.

**Comment by amineamali** [comment]
Thank you for the clarification and for the great work, it went very well on my own dataset.
