### ISSUE TITLE
memory error

### ISSUE THREAD

**Issue by xingchenzhang** [aras62/PIEPredict#12]
Hi,

Many thanks for your nice work. 

When I tried to run test using only seq1, I have memory error. I am wondering how much memory actually needed to run this model? Could you share some ideas? I have 16G memory, it seems that it is not enough..

Best wishes,
Xingchen

**Comment by aras62** [comment]
Hi, 

We specified that you need about 32 GB memory for running the code as-is. Alternatively, if you have issues with memory limits, you can consider creating a Datagenerator
