### ISSUE TITLE
De-normalizing bounding box coordinates 

### ISSUE THREAD

**Issue by trungmanhhuynh** [aras62/PIEPredict#20]
Hi, 

Thank you much for such a great work !. I am trying to understand how you de-normalize bounding box coordinates before evaluating the performance.

I understood that you normalized it by subtracting the box's coordinate in the first frame, but when I see the code below: 
```
       perf = {}
        performance = np.square(test_results - box_data['pred_target'])
        perf['mse-15'] = performance[:, 0:15, :].mean(axis=None)
        perf['mse-30'] = performance[:, 0:30, :].mean(axis=None)  # 15:30
        perf['mse-45'] = performance.mean(axis=None)
        perf['mse-last'] = performance[:, -1, :].mean(axis=None)
```
in https://github.com/aras62/PIEPredict/blob/473e43db0f65ffbff321355211337b13c22da7a9/pie_predict.py#L567 

You dont covert it back to actual pixel coordinates before calculating MSE for bounding box. I see that you do this denormalization for the centers before calculating C-MSE, which is correct to my thought, but this does not apply to bounding box coordinates ?

Could you please shed a light to this ? I believe that I am missing something here.

Thank you very much,

**Comment by aras62** [comment]
Hi,

So the ground truth that I used to compute metrics is also normalized, therefore there is no need to convert back. For the centers, I convert back both the results and the ground truth in order to compute the center coordinates.

**Comment by trungmanhhuynh** [comment]
@aras62  Thanks a lot, it makes sense. I think I understand it now. I wonder if we don't convert back the centers for evaluating it, we can still get the same results (with converting back), right ? Because what you've implemented for normalization is subtracting to the starting points and without using standard normalization.
