### ISSUE TITLE
pie_path

### ISSUE THREAD

**Issue by guofengpeng** [aras62/PIEPredict#3]
hi sir,  I`m so sorry to bother you.
when i input "python train_test.py 1", it will occur :
-----------------------------------------------------------------------------------
Using TensorFlow backend.
Traceback (most recent call last):
  File "train_test.py", line 182, in <module>
    main(train_test=train_test)
  File "train_test.py", line 175, in main
    intent_model_path = train_intent(train_test=train_test)
  File "train_test.py", line 135, in train_intent
    imdb = PIE(data_path=os.environ.copy()['PIE_PATH'])
  File "/home/guofengpeng/my/pie/PIEPredict/pie_data.py", line 57, in __init__
    'pie path does not exist: {}'.format(self._pie_path)
AssertionError: pie path does not exist: /path/to/PIE/data/root
----------------------------------------------------------------------------------
but i cannot find where  write "/path/to/PIE/data/root".

**Comment by ykotseruba** [comment]
The ```path/to/PIE/data/root``` is a placeholder, it should be changed to the directory where the PIE dataset is stored on your computer.

**Comment by guofengpeng** [comment]
thanks，my brothor.
