### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by guofengpeng** [aras62/PIEPredict#4]
hi sir, when I down the PIE ,  the /PIE/  has 3 zip (annotations.zip, annotations_attributes.zip and annotations_vehicle.zip).  however , according to github  in /PIEPredict/PIE_dataset , it need only annotations folder. I need copy set01-06 from annotations_attributes  and annotations_vehicle , is true?

**Comment by ykotseruba** [comment]
Please unarchive all annotation zip files. Each annotation directory should have `set01`-`set06` directories, they should not be merged.

```
PIE_dataset
    annotations
        set01
        ...
    annotations_attributes
        set01
        ...
    annotations_vehicles
        set01
        ...
    PIE_clips
        set01
        ...
```

**Comment by guofengpeng** [comment]
thanks,sir. due to my station disk is just 1T, I only down set01 and set02 , and change the "pie_data.py" about val, train, test and all.  about at 15:30(beijing time),I have run the train, but it failed after 10 min. crying...

**Comment by ykotseruba** [comment]
As we mention in the readme, at least 1.1TB  of disk space is required to store the data and cached features, the current version of the code does not support partial loading of the data. You will also need 32GB RAM to run pie_intent model. 
If you modified the code in `pie_data.py` I will not be able to resolve the issue you are having.

**Comment by guofengpeng** [comment]
oh，thanks sir. 
if I record a paragraph vedio in my local environment, the video cropped will be placed at set01-06. So how can I make annotations?  which ways you chose? by manual?

**Comment by ykotseruba** [comment]
Yes, the annotations were made manually using [cvat](https://github.com/opencv/cvat/).

**Comment by guofengpeng** [comment]
thank you very much, my brother!
