### ISSUE TITLE
How to generate annotations_attributes for custom dataset

### ISSUE THREAD

**Issue by poornimajd** [aras62/PIEPredict#5]
Hello, great work @ykotseruba and team!
I was trying to use the piepredict model on custom dataset to predict pedestrian intention,but I am not sure how did you generate the annotation_attributes.zip (under pi dataset),using cvat tool.
I was able to generate the annotations using cvat tool ,but I am wondering how to get annotation_attributes.
Any suggestion is greatly appreciated!
Thanks.

**Comment by ykotseruba** [comment]
Hi @poornimajd,
You don't need to use cvat to create attribute annotations. You can make a table (e.g. excel spreadsheet) and then convert it to XML or create an XML directly. For each pedestrian track, you need to define a set of attributes as explained in [PIE annotations readme](https://github.com/aras62/PIE). If some of the attributes are missing in your dataset, provide a dummy value to avoid modifying the `pie_data.py` interface.

**Comment by poornimajd** [comment]
Thanks for the quick and detailed reply!
