### ISSUE TITLE
how to use the model

### ISSUE THREAD

**Issue by guofengpeng** [aras62/PIEPredict#6]
Holle，sir, thank your great job!
I have train the model, but I want to see the effect. I want to take a video ( or use a video from the datasets) , then input the model. At last I hope get a video annotated by the model. Please teach me how to use , thank.

**Comment by aras62** [comment]
Hi, 
Thanks for using our code. Regarding the code for generating demo, unfortunately we cannot provide you with customized code. For any modifications or new code please either follow the code documentation or refer to online forums for samples.

**Comment by guofengpeng** [comment]
I donot need customized code. When I have trained the model, I need to transfor a clip of vedio ( not include annotations). but your paper said the model alse needs to input speed of car and other information.
So i want to know how to use the model. In your code, not provide the ways.

**Comment by ykotseruba** [comment]
Hi, 
if I understood your first question correctly, you would like to visualize the results of the model. Unfortunately, current release of the code does not provide any visualizations. If you would like to run the model on an arbitrary video clip (not from the dataset) the video should have the same annotations as the videos in the PIE dataset and `pie_data` interface should be modified to parse the new annotations.

**Comment by guofengpeng** [comment]
yes，you are right. 
Using the CVAT tool can annotate the image. 
however in annotations_vehicle folder and annotations_attributes folder, what tool can be used.
