### ISSUE TITLE
trajectory

### ISSUE THREAD

**Issue by guofengpeng** [aras62/PIEPredict#8]
hi sir, I disturb again, sorry.
when I use 'python train_test.py 2', (the input is set03), I hope I can use opencv to display the trajectory.  the output is like this image from ‘https://github.com/YapingZ/Pedestrian-behavior-trajectory-prediction’.
So, how can I get the value of 'x' and 'y' from output data?

**Comment by aras62** [comment]
Hi, 

The interface is well documented. Please follow the documentation in the code to understand the data format. Perhaps you want to take a look at generate_database()
